In [1]:
import torch
import torch.nn as nn

In [2]:
layer1 = torch.tensor([1, 2, 3, 2], dtype=torch.float32).view(1, 4)
layer1.shape

torch.Size([1, 4])

In [3]:
layer1

tensor([[1., 2., 3., 2.]])

In [4]:
mu = layer1.mean()
std = layer1.std(unbiased=False)
std_unbiased = layer1.std(unbiased=True)

mu, std, std_unbiased

(tensor(2.), tensor(0.7071), tensor(0.8165))

In [5]:
(layer1 - mu) / std

tensor([[-1.4142,  0.0000,  1.4142,  0.0000]])

In [6]:
img = torch.tensor([
    [0, 1, 0],
    [1, 1, 1],
    [0, 1, 0],
], dtype=torch.float32)
img.shape

img = torch.rand(3, 3, 4, dtype=torch.float32)
img.shape

torch.Size([3, 3, 4])

In [7]:
img_mu = img.mean()
img_std = img.std(unbiased=False)

print(img_mu, img_std)

(img - img_mu) / img_std

tensor(0.4989) tensor(0.2660)


tensor([[[ 1.0597e+00, -5.0324e-01, -1.1764e+00,  9.0194e-01],
         [-1.1851e+00, -3.9531e-01, -2.4128e-01, -1.0102e+00],
         [-4.9040e-01,  3.1877e-01,  1.4960e+00,  6.5003e-01]],

        [[-1.2821e+00,  7.3137e-04,  1.7822e-01,  1.2907e+00],
         [-1.6243e+00, -1.8568e+00, -5.7848e-01,  1.2601e+00],
         [ 1.6675e+00,  1.7227e+00, -1.1457e-01, -2.6693e-01]],

        [[ 9.5934e-01, -1.3406e-01, -1.1104e+00,  1.5900e+00],
         [-1.3752e+00, -6.3234e-01, -2.9072e-02,  6.8610e-01],
         [-4.8901e-01,  1.1849e+00,  2.0313e-01, -6.7456e-01]]])

In [8]:
layer_norm: torch.nn.LayerNorm = torch.nn.LayerNorm((3, 3, 4), eps=0)

layer_norm(img)
layer_norm.weight.shape, layer_norm.bias.shape
# layer_norm.weight

(torch.Size([3, 3, 4]), torch.Size([3, 3, 4]))

In [9]:
group_norm = nn.GroupNorm(8, 8)

group_norm.weight.shape, group_norm.bias.shape

(torch.Size([8]), torch.Size([8]))